// AI Workbench 错误码集中定义。
// 客户端按此编码做 i18n 与错误处理；后端中间件/路由统一从这里取。

export const ERROR_CODES = Object.freeze({
  // 输入
  INVALID_INPUT: "INVALID_INPUT",
  EMPTY_INPUT: "EMPTY_INPUT",
  INPUT_TOO_LARGE: "INPUT_TOO_LARGE",
  UNSUPPORTED_SOURCE_TYPE: "UNSUPPORTED_SOURCE_TYPE",
  // 重复/已存在
  DUPLICATE_TASK_DRAFT: "DUPLICATE_TASK_DRAFT",
  TASK_DRAFT_ALREADY_FINALIZED: "TASK_DRAFT_ALREADY_FINALIZED",
  // 解析
  PARSE_FAILED: "PARSE_FAILED",
  NORMALIZATION_FAILED: "NORMALIZATION_FAILED",
  // 资源
  MAIN_PROJECT_NOT_FOUND: "MAIN_PROJECT_NOT_FOUND",
  MAIN_PROJECT_AMBIGUOUS: "MAIN_PROJECT_AMBIGUOUS",
  REPOSITORY_NOT_FOUND: "REPOSITORY_NOT_FOUND",
  REPOSITORY_PROJECT_MISMATCH: "REPOSITORY_PROJECT_MISMATCH",
  TARGET_BRANCH_NOT_FOUND: "TARGET_BRANCH_NOT_FOUND",
  BASE_BRANCH_NOT_FOUND: "BASE_BRANCH_NOT_FOUND",
  FLAVOR_NOT_FOUND: "FLAVOR_NOT_FOUND",
  DEPENDENCY_NOT_FOUND: "DEPENDENCY_NOT_FOUND",
  // 推导
  INFERENCE_FAILED: "INFERENCE_FAILED",
  INFERENCE_TIMEOUT: "INFERENCE_TIMEOUT",
  INFERENCE_RATE_LIMITED: "INFERENCE_RATE_LIMITED",
  // 校验/复核/预检
  VALIDATION_FAILED: "VALIDATION_FAILED",
  REVIEW_FAILED: "REVIEW_FAILED",
  PRECHECK_FAILED: "PRECHECK_FAILED",
  BLOCKER_NOT_REPAIRED: "BLOCKER_NOT_REPAIRED",
  // 修复
  REPAIR_EXHAUSTED: "REPAIR_EXHAUSTED",
  REPAIR_STRATEGY_NOT_FOUND: "REPAIR_STRATEGY_NOT_FOUND",
  // 批次
  BATCH_ALREADY_RUNNING: "BATCH_ALREADY_RUNNING",
  BATCH_NOT_PAUSED: "BATCH_NOT_PAUSED",
  BATCH_NOT_PENDING: "BATCH_NOT_PENDING",
  BATCH_TOO_LARGE: "BATCH_TOO_LARGE",
  BATCH_EMPTY: "BATCH_EMPTY",
  BATCH_HAS_RUNNING_ITEMS: "BATCH_HAS_RUNNING_ITEMS",
  // 故事点
  STORY_POINT_ALREADY_CREATED: "STORY_POINT_ALREADY_CREATED",
  STORY_POINT_CREATE_FAILED: "STORY_POINT_CREATE_FAILED",
  STORY_POINT_LOCKED: "STORY_POINT_LOCKED",
  // 锁
  RESOURCE_LOCKED: "RESOURCE_LOCKED",
  RESOURCE_LOCK_EXPIRED: "RESOURCE_LOCK_EXPIRED",
  // 配置
  CONFIG_FIELD_LOCKED: "CONFIG_FIELD_LOCKED",
  CONFIG_FIELD_NOT_FOUND: "CONFIG_FIELD_NOT_FOUND",
  CONFIG_INVALID_VALUE: "CONFIG_INVALID_VALUE",
  CONFIG_FINGERPRINT_MISMATCH: "CONFIG_FINGERPRINT_MISMATCH",
  // 权限
  PERMISSION_DENIED: "PERMISSION_DENIED",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  // 队列
  QUEUE_FULL: "QUEUE_FULL",
  QUEUE_SHUTDOWN: "QUEUE_SHUTDOWN",
  // 系统
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
});

export class AiautoworkError extends Error {
  constructor(code, message, { httpStatus = 400, details = null, cause = null } = {}) {
    super(message || code);
    this.name = "AiautoworkError";
    this.code = code;
    this.httpStatus = httpStatus;
    this.details = details;
    if (cause) this.cause = cause;
  }
  toJSON() {
    return {
      ok: false,
      error: {
        code: this.code,
        message: this.message,
        details: this.details,
      },
    };
  }
}

export function toAiautoworkError(code, message, opts = {}) {
  return new AiautoworkError(code, message, opts);
}
